#!/usr/bin/env bash
set -eo pipefail; [[ $DOKKU_TRACE ]] && set -x
source "$(dirname $0)/../common/functions"
source "$(dirname $0)/config"

dokku_log_info1 "Running webhooks"

[[ -f "$HOOKS_FILE" ]] || exit

while read url; do
  dokku_log_info2_quiet "$url"
done < "$HOOKS_FILE"
