#!/usr/bin/env bash
set -eo pipefail; [[ $DOKKU_TRACE ]] && set -x

APP=$1; PORT=$2; IP=$3

"$(dirname $0)"/trigger post-deploy $APP \
  internal_port=$PORT \
  internal_ip=$IP \
  url=$(dokku url $APP)
